name: Docs Lint

on:
  push:
    paths:
      - 'GOVERNANCE.md'
      - 'CONTRIBUTING.md'
  pull_request:
    paths:
      - 'GOVERNANCE.md'
      - 'CONTRIBUTING.md'

jobs:
  lint-gov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install markdownlint
        run: |
          npm install -g markdownlint-cli
      - name: Run markdownlint
        run: markdownlint GOVERNANCE.md CONTRIBUTING.md
